"""Константы приложения"""

# Цвета
COLOR_CARD_BG = "#f5f5dc"
COLOR_CARD_HEADER = "#4169E1"
COLOR_CARD_BORDER = "#4169E1"
COLOR_CARD_SELECTED = "#DC143C"
COLOR_CONNECTION = "#666666"
COLOR_CONNECTION_SELECTED = "#DC143C"
COLOR_ANCHOR = "#FF6B6B"
COLOR_ANCHOR_HOVER = "#FF4444"
COLOR_GRID = "#e0e0e0"
COLOR_SCENE_BG = "#fafafa"
COLOR_ATTR_TEXT = "#2c3e50"
COLOR_METHOD_TEXT = "#27ae60"

# Размеры
CARD_WIDTH = 160
CARD_HEIGHT_MIN = 100
CARD_HEADER_HEIGHT = 30
ANCHOR_SIZE = 8
ARROW_SIZE = 12
GRID_SIZE = 50

# Шрифты
FONT_FAMILY = "Arial"
FONT_SIZE_TITLE = 10
FONT_SIZE_CONTENT = 9
FONT_FAMILY_CODE = "Menlo"

# Пути
DATA_DIR = "data"
SAVES_DIR = "data/saves"
EXPORTS_DIR = "data/exports"

# Форматы
SUPPORTED_IMAGE_FORMATS = ["png", "svg", "jpg"]
SUPPORTED_CODE_LANGUAGES = ["python", "java", "javascript"]